CONF.isDefinition = true;
RESIZE('/*.jpg', '50%');
MERGE('/merge.js', '/js/test.js', 'file.txt');
MERGE('/merge-blocks-a.js', '/js/block.js#a,c,d');
MERGE('/merge-blocks-b.js', '/js/block.js#b');
MAP('/fet.txt', framework.path.public('file.txt'));
MAP('/blocks-a.js', '/js/block.js#a,c,d');
MAP('/blocks-b.js', '/js/block.js#b');
MAP('/blocks-c.js', '/js/block.js#a,b');
MERGE('/merge-theme.js', '=green/public/js/default.js', '=green/public/js/merge.js');
MAP('/map-theme.js', '=green/public/js/default.js');